#!/bin/bash -e

source lib/functions.sh

CWD=$(pwd)
umask 022

if [ "$1" == "" ]; then
  msg "Please specify a architecture to build."
  exit 1
fi

if ! test -f targets/$1.tgt; then
  msg "$1 target file does not exist."
  exit 1
fi

chmod +x targets/$1.tgt
source targets/$1.tgt

set --

cat > $CWD/bootstrap.env << EOF
## BOOTSTRAP ENV FILE ##
umask 022

STRAP_CWD=$CWD
STRAP_ROOTFS=$STRAP_ROOTFS
STRAP_SOURCES=$STRAP_ROOTFS/sources
STRAP_KARCH=$STRAP_KARCH
STRAP_HOST=$(echo ${MACHTYPE} | sed "s/-[^-]*/-cross/")
STRAP_TARGET=$STRAP_TARGET
export STRAP_CWD STRAP_ROOTFS STRAP_SOURCES STRAP_HOST STRAP_TARGET

LC_ALL=POSIX
PS1='\u:\w\$ '
TERM=$TERM
PATH=${STRAP_ROOTFS}/cross-tools/bin:/bin:/usr/bin
export PATH LC_ALL PS1 TERM
## END OF ENV ##
EOF

msg "Below is the bootstrap enviroment file..."

cat $CWD/bootstrap.env

msg "End of bootstrap enviroment file..."

chmod +x $CWD/bootstrap.env

source $CWD/bootstrap.env

msg "Creating progress directory..."

mkdir -vp $CWD/progress

msg "Creating rootfs directory..."

mkdir -vp "$STRAP_ROOTFS"

mkdir -vp "$STRAP_SOURCES"
