#!/bin/bash -e

source lib/functions.sh

CWD=$(pwd)
umask 022

STRAP_ROOTFS=$CWD/rootfs

msg "Testing proot execution..."

proot_run_cmd_tools $1 "ls -la"

msg "Injecting dummy.c..."

echo 'int main(){}' > $STRAP_ROOTFS/dummy.c

msg "Compiling dummy.c..."

proot_run_cmd_tools $1 "cc dummy.c -v -Wl,--verbose &> dummy.log"

msg "Looking at sanity check..."

proot_run_cmd_tools $1 "readelf -l a.out | grep ': /lib'"

msg "Checking start files in log..."

grep -o '/usr/lib.*/crt[1in].*succeeded' $STRAP_ROOTFS/dummy.log

msg "Verify search of correct header files in log..."

grep -B4 '^ /usr/include' $STRAP_ROOTFS/dummy.log

msg "Verify linker in log..."

grep 'SEARCH.*/usr/lib' $STRAP_ROOTFS/dummy.log |sed 's|; |\n|g'

msg "Verify correct glibc in log..."

grep "/lib.*/libc.so.6 " $STRAP_ROOTFS/dummy.log

msg "Verify correct dynamic linker in log..."

grep found $STRAP_ROOTFS/dummy.log

msg "Done with tests..."