#!/bin/bash -e

source lib/functions.sh

CWD=$(pwd)
umask 022

STRAP_ROOTFS=$CWD/rootfs

msg "Testing proot execution..."

proot_run_cmd_tools $1 "ls -la"

msg "Injecting dummy.c..."

echo 'int main(){}' > $STRAP_ROOTFS/dummy.c

msg "Compiling dummy.c..."

proot_run_cmd_tools $1 "cc dummy.c -v -Wl,--verbose &> dummy.log"

msg "Looking at sanity check..."

proot_run_cmd_tools $1 "readelf -l a.out"

msg "Output log..."

cat $STRAP_ROOTFS/dummy.log

msg "Done with tests..."