name: Multi-Arch Bootstraper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:
    name: Build toolchain and rootfs
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        target-arch: [x86_64, aarch64]
    env:
      ACTION_TGT_ARCH: ${{matrix.target-arch}}
      DEBIAN_FRONTEND: noninteractive
      SCP_USER: ${{ secrets.USERNAME }}
      SCP_PASS: ${{ secrets.PASSWORD }}
      SCP_HOST: ${{ secrets.HOST }}
      SCP_PORT: ${{ secrets.PORT }}
    steps:
    ### Setup OS enviroment ###
    - uses: actions/checkout@v2
    - name: install / update deps if not installed
      run: sudo apt update -y && sudo apt install sshpass scp rsync build-essential expect pkg-config libarchive-tools m4 gawk bc bison flex texinfo python3 perl libtool autoconf automake autopoint autoconf-archive mtools liblzma-dev libelf-dev libssl-dev zlib1g-dev zlib1g xz-utils lzip file curl wget gettext -y && sudo apt autoremove -y
    - name: use bash instead of dash
      run: sudo dpkg-reconfigure dash
    - name: move bashrc file outside of current user
      run: sudo mv -fv /etc/bash.bashrc /etc/bash.bashrc.NOUSE | true
    ### Actually run bootstrap process ###
    - name: setup bootstrap
      run: ./strap-setup $ACTION_TGT_ARCH
    - name: build toolchain
      run: ./strap-toolchain $ACTION_TGT_ARCH
    - name: build chroot
      run: ./strap-chroot $ACTION_TGT_ARCH
    ### Upload artifacts ###
    - name: change ownership and archive stage 1 rootfs
      if: ${{ always() }}
      run: cp -r ${GITHUB_WORKSPACE}/logs ${GITHUB_WORKSPACE}/rootfs && sudo chown root:root -R ${GITHUB_WORKSPACE}/rootfs && sudo tar -cJf ${GITHUB_WORKSPACE}/stage-1-rootfs-$ACTION_TGT_ARCH.tar.xz -C ${GITHUB_WORKSPACE}/rootfs .
    - name: prep for upload
      run: cp ${GITHUB_WORKSPACE}/stage-1-rootfs-$ACTION_TGT_ARCH.tar.xz ${GITHUB_WORKSPACE}/stage-1-rootfs-$ACTION_TGT_ARCH--${{github.run_id}}.tar.xz
    - name: upload rootfs to server
      run: sshpass -p '$SCP_PASS' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P $SCP_PORT stage-1-rootfs-${{matrix.target-arch}}-${{github.run_id}}.tar.xz $SCP_USER@$SCP_HOST:/var/www/files.jlab.space/actions/bootstrap
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: stage-1-rootfs-${{matrix.target-arch}}-${{github.run_id}} 
        path: ${{github.workspace}}/stage-1-rootfs-${{matrix.target-arch}}.tar.xz
  test:
    name: Test rootfs
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      fail-fast: false
      matrix:
        target-arch: [x86_64, aarch64]
    env:
      ACTION_TGT_ARCH: ${{matrix.target-arch}}
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: install / update deps if not installed
        run: sudo apt update -y && sudo apt install rsync wget curl proot qemu qemu-user-static elfutils -y && sudo apt autoremove -y
      - name: download rootfs artifact
        uses: actions/download-artifact@v2
        with:
          name: stage-1-rootfs-${{matrix.target-arch}}-${{github.run_id}}
      - name: extract rootfs
        run: mkdir rootfs && tar -xf ${GITHUB_WORKSPACE}/stage-1-rootfs-$ACTION_TGT_ARCH.tar.xz -C rootfs
      - name: move scripts to current directory.
        run: cp -v ${GITHUB_WORKSPACE}/.github/workflows/scripts/* ${GITHUB_WORKSPACE}
      - name: test rootfs
        run: sudo ./test-rootfs $ACTION_TGT_ARCH 
