name: Multi-Arch Builder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        target-arch: [x86_64, aarch64]
    env:
      ACTION_TGT_ARCH: ${{matrix.target-arch}}
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v2
    - name: install / update deps if not installed
      run: sudo apt update -y && sudo apt install rsync build-essential expect pkg-config libarchive-tools m4 gawk bc bison flex texinfo python3 perl libtool autoconf automake autopoint autoconf-archive mtools liblzma-dev libelf-dev libssl-dev zlib1g-dev zlib1g xz-utils lzip file curl wget gettext -y && sudo apt autoremove -y
    - name: use bash instead of dash
      run: sudo dpkg-reconfigure dash
    - name: change shell scripts permissions
      run: chmod +x -R ./*.sh
    - name: move bashrc file outside of current user
      run: sudo mv -fv /etc/bash.bashrc /etc/bash.bashrc.NOUSE | true
    - name: add tools symlink.
      run: sudo ln -sv ${GITHUB_WORKSPACE}/rootfs/tools /
    - name: setup
      run: ./setup.sh
    - name: build toolchain
      run: ./build-toolchain.sh $ACTION_TGT_ARCH
    - name: build chroot
      run: ./build-chroot.sh $ACTION_TGT_ARCH
    - name: change ownership and archive stage 1 rootfs
      if: ${{ always() }}
      run: sudo chown root:root -v -R ./rootfs ./toolchain && sudo tar -cJf stage1-rootfs-$ACTION_TGT_ARCH.tar.xz -C ./rootfs . && sudo tar -cJf toolchain-$ACTION_TGT_ARCH.tar.xz -C ./toolchain .
    - name: archive debug
      if: ${{ always() }}
      run: sudo tar -cJf debug-$ACTION_TGT_ARCH.tar.xz -C gcc-10.1.0
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: stage1-rootfs-${{matrix.target-arch}}-${{github.run_id}} 
        path: ${{github.workspace}}/stage1-rootfs-${{matrix.target-arch}}.tar.xz
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: toolchain-${{matrix.target-arch}}-${{github.run_id}} 
        path: ${{github.workspace}}/debug-${{matrix.target-arch}}.tar.xz
