name: Multi-Arch Builder

on:
  push:
    branches: [ alt-bootstrap ]
  pull_request:
    branches: [ alt-bootstrap ]

jobs:  
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        target-arch: [x86_64, aarch64]
    env:
      ACTION_TGT_ARCH: ${{matrix.target-arch}}
      DEBIAN_FRONTEND: noninteractive
    steps:
    ### Setup OS enviroment ###
    - uses: actions/checkout@v2
    - name: install / update deps if not installed
      run: sudo apt update -y && sudo apt install rsync build-essential expect pkg-config libarchive-tools m4 gawk bc bison flex texinfo python3 perl libtool autoconf automake autopoint autoconf-archive mtools liblzma-dev libelf-dev libssl-dev zlib1g-dev zlib1g xz-utils lzip file curl wget gettext -y && sudo apt autoremove -y
    - name: use bash instead of dash
      run: sudo dpkg-reconfigure dash
    - name: move bashrc file outside of current user
      run: sudo mv -fv /etc/bash.bashrc /etc/bash.bashrc.NOUSE | true
    ### Actually run bootstrap process ###
    - name: setup
      run: ./setup $ACTION_TGT_ARCH
    - name: build toolchain
      run: ./strap-toolchain $ACTION_TGT_ARCH
    ### Post steps ###
    - name: change ownership and archive stage 1 rootfs
      if: ${{ always() }}
      run: cp ${GITHUB_WORKSPACE}/logs rootfs/logs && sudo chown root:root -v -R ${GITHUB_WORKSPACE}/rootfs && sudo tar -cJf ${GITHUB_WORKSPACE}/rootfs-$ACTION_TGT_ARCH.tar.xz -C ${GITHUB_WORKSPACE}/rootfs .
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: rootfs-${{matrix.target-arch}}-${{github.run_id}} 
        path: ${{github.workspace}}/rootfs-${{matrix.target-arch}}.tar.xz
